### ISSUE TITLE
Recommended For You 

### ISSUE THREAD

**Issue by waelkamira** [202303-PRM-TR-FEW/capstone-learning-app-team-6#13]
Description:
Create a Recommended Component, based on the design provided in Uizard, and help others with any issues during the first sprint.

Design reference: [Design link](https://app.uizard.io/templates/O4wRKled8RU1mmnLlGgb/fullscreen)

**Comment by Edriss572** [comment]
this components is complete and ready to be tested and embeded

**Comment by Mohammad-Ayman** [comment]
Hello @Edriss572 , please check it's responsivity and the height of each image.

**Comment by Edriss572** [comment]
i just fix the width problem
