### ISSUE TITLE
Courses & Saved (add functionality)

### ISSUE THREAD

**Issue by danzym** [202303-PRM-TR-FEW/capstone-learning-app-team-6#37]
Add functionality to the saved and courses pages. Organize and display fetched information.

Design reference: [Design link](https://app.uizard.io/templates/O4wRKled8RU1mmnLlGgb/fullscreen)

**Comment by Mohammad-Ayman** [comment]
Functionality working on local data.

Working on adjusting data from firebase

**Comment by Mohammad-Ayman** [comment]
Done
